# Generated by Django 5.0.6 on 2024-06-30 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='taskmanage',
            table='tasks list',
        ),
    ]
